name: Check version
on: push

jobs: 
  run:
    name: Check version
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master

    - name: Check
      id: check
      uses: EndBug/version-check@debug

    - env:
        C: ${{ steps.check.outputs.changed }}
        T: ${{ steps.check.outputs.type }}
      run: 'echo $C $T'