name: Add tag
on: push

jobs: 
  run:
    name: Tag
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.0.0

    - run: npm start
      with:
        registry:
        - npm
        - url: 'https://github.com'
          token: '123456789'
          