name: Test
on: push

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: "./pathToRepo/"

      - uses: EndBug/add-and-commit@dist
        with:
          message: "Test"
          add: "*.txt"
          cwd: "./pathToRepo/"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
