name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "123" >> file1.txt
      - run: echo "123" >> file2.txt


      - uses: ocean90/add-and-commit@try/github-actor
        with:
          add: "['file1.txt -f', 'file2.txt -f']"
          message: add
          push: false
          author_name: Ajeje
          
                
      - uses: ocean90/add-and-commit@try/github-actor
        with:
          remove: '["file1.txt -f", "file2.txt -f"]'
          message: remove
          push: 'origin add-and-commit --force'
          author_email: lol@example.com
