name: Write file
on: push

jobs: 
  run:
    name: Write file
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@master

    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 10.0.0
    
    - name: Start
      run: npm start

    - run: ls

    - name: Commit documentation changes
      uses: EndBug/add-and-commit@test
      with:
        commit_author_name: Federico Grandi
        commit_author_email: fgrandi30@gmail.com
        commit_message: "[test] Write date file"
        commit_path: ./*.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
