name: Test
on: push

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "123" > file2.txt

      - uses: EndBug/add-and-commit@dist
        with:
          message: "Test"
          path: "."
          pattern: "*.txt"
          force: false
          remove: file.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
