name: Test
on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@master
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}
          file-name: ./.github/../package.json
          file-url: https://raw.githubusercontent.com/EndBug/temp-action-test/ddbbb101b54f389ac97e25e797d4bb91721a1549/package.json
          assume-same-version: old

      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found in commit ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed != 'true'
        run: 'echo "No version change :/"'
