name: Test
on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/export-label-config@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-aliases: false
          raw-result: true
        
