name: Test
on:
  schedule:
    - cron: "* * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "123" >> file.txt

      - uses: EndBug/add-and-commit@master
        with:
          message: "Test"
          add: "*.txt"
          remove: "*.none"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@master
        with:
          message: "Test"
          add: "*.none"
          remove: "*.txt"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
