name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "123" >> file.txt

      - run: echo $HOME

      - uses: EndBug/add-and-commit@master
        with:
          add: '*.txt -f'
          message: add
          tag: lol
          push: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - run: git show lol --name-only
                
      - uses: EndBug/add-and-commit@master
        with:
          remove: '*.asd -f'
          message: remove
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
