name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "123" >> other.file

      - uses: RobinWijnant/add-and-commit@master
        with:
          message: "Test"
          add: "*.txt"
          remove: "*.none"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
