name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          path: "./pathToRepo/"

      - run: mkdir ./pathToRepo/
      - run: echo "123" > ./pathToRepo/file.txt

      - uses: EndBug/add-and-commit@cwd
        with:
          message: "Test"
          path: "."
          pattern: "*.txt"
          cwd: "./pathToRepo/"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
