name: Check version
on: push

jobs: 
  edit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: 'echo "Write this!" >> file.txt'
    - uses: EndBug/add-and-commit@v2.1.0
      with:
        pattern: '*.txt'
        force: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    needs: edit

    steps:
    - uses: actions/checkout@master
      with:
        ref: master
    - run: cat file.txt