name: Test
on:
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: EndBug/label-sync@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }]
          source-repo: EndBug/add-and-commit
          dry-run: true
