name: Test
on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1.1.0

      - name: Log when changed
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.steps.check.outputs.type }})"'

      - name: Log when unchanged
        if: steps.check.outputs.changed != 'true'
        run: 'echo "No version change :/"'
