name: Test
on:
  release:
    types: [published]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/latest-tag@master
        with:
          description: test description
          tag-name: customname

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
