name: Test
on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - run: echo "123" > file.txt

      - uses: EndBug/add-and-commit@dist
        with:
          message: "Your commit message"
          path: "."
          pattern: "*.txt"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
