name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "123" >> file.txt

      - uses: EndBug/add-and-commit@master
        with:
          message: "Test"
          add: "*.txt"
          remove: "*.none"
          tag: newTag-fileAdd
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: EndBug/add-and-commit@master
        with:
          message: "Test"
          add: "*.none"
          remove: "*.txt"
          tag: newTag-fileRem
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
