name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: aac-ref

      - run: echo "123" >> file.txt

      - uses: ToMe25/add-and-commit@master
        with:
          message: "Test"
          add: "*.txt"
          remove: "*.none"
          tag: newTag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
