name: Test
on: push

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "123" > ./dir/file1.txt
      - run: echo "123" > ./file2.txt
      - run: ls

      - uses: EndBug/add-and-commit@dist
        with:
          message: "Test1"
          path: "."
          pattern: "*.txt"
          force: false
          # find_args: '. -name "*.txt"'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
