name: Test
on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test step
        run: echo $UBI_EMAIL $UBI_PASSWORD
        env:
          UBI_EMAIL: ${{ secrets.UBI_EMAIL }}
          UBI_PASSWORD: ${{ secrets.UBI_PASSWORD }}
