name: Test
on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "123" >> file1.txt
      - run: echo "123" >> file2.txt


      - uses: EndBug/add-and-commit@v7
        with:
          add: "['file1.txt -f', 'file2.txt -f']"
          message: add
          author_name: github-actions
          author_email: email@example.com
          
                
      - uses: EndBug/add-and-commit@v7
        with:
          remove: '["file1.txt -f", "file2.txt -f"]'
          message: remove
          author_name: github-actions
          author_email: actions@github.com
