name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "123" >> file1.txt

      - run: echo $HOME

      - uses: EndBug/add-and-commit@yaml-arrays
        with:
          add: "['file1.txt -f']"
          message: add
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                
      - uses: EndBug/add-and-commit@yaml-arrays
        with:
          remove: '*.txt -f'
          message: remove
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
