name: Test
on:
  push:
    tags-ignore:
      - '*'
    paths:
      - package.json

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test step
        run: echo abc
