name: Test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - run: echo "123" >> file1.txt
      - run: echo "123" >> file2.txt

      - run: echo $HOME

      - uses: EndBug/add-and-commit@master
        with:
          add: "['file1.txt -f', 'file2.txt -f']"
          message: add
          push: false
          author_name: Ajeje
          author_email: lol@example.com
                
      - uses: EndBug/add-and-commit@master
        with:
          remove: '["file1.txt -f", "file2.txt -f"]'
          message: remove
          push: 'origin add-and-commit --force'

