name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     shell: bash

    steps:
      - uses: actions/checkout@v2

      - run: echo "123" >> file.txt

      - uses: pvogt09/add-and-commit@master
        with:
          message: "Test1"
          add: "*.txt"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: pvogt09/add-and-commit@master
        with:
          message: "Test2"
          add: "*.txt"
          force: true
          signoff: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: pvogt09/add-and-commit@master
        with:
          message: "Test3"
          remove: "*.txt"
          force: true
          signoff: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
