name: Test
on:
  release:
    types: [published]
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/latest-tag@master
