name: Test
on: push

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "456" > dir/file2.txt

      - uses: EndBug/add-and-commit@dist
        with:
          message: "Test"
          path: "dir"
          pattern: "*.txt"
          force: false
          remove: dir/file1.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
