name: Test
on: push

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: EndBug/add-and-commit@dist
        with:
          message: "Test"
          path: "."
          pattern: "*.*"
          force: false
          remove: dir -r
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
