name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     shell: bash

    steps:
      - uses: actions/checkout@v2

      - run: echo "123" >> file.txt

      - uses: EndBug/add-and-commit@master
        with:
          message: "Test"
          add: "*.txt"
          remove: "*.none"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - uses: EndBug/add-and-commit@master
      #   with:
      #     message: "Test"
      #     add: "*.none"
      #     remove: "*.txt"
      #     force: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
