name: Test
on: 
  push:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@latest
        with:
          diff-search: true
          token: ${{ secrets.GITHUB_TOKEN }}
          file-name: ./.github/../package.json

      - name: Log changed
        run: 'echo "Version has changed? ${{ steps.check.outputs.changed }} ${{ steps.check.outputs.commit }}! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'
