name: Add tag
on:
  release:
    types: [published]

jobs: 
  run:
    name: Tag
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout

    - uses: 'EndBug/latest-tag@master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}