name: Test
on: push

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          path: "./pathToRepo/"

      - run: echo "123" > ./pathToRepo/file1.txt

      - uses: EndBug/add-and-commit@v2
        with:
          message: "Test1"
          path: "."
          pattern: "*.txt"
          cwd: "./pathToRepo/"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test2:
    runs-on: ubuntu-latest
    needs: test1

    steps:
      - uses: actions/checkout@v2
        with:
          path: "./pathToRepo/"

      - run: echo "123" > ./pathToRepo/file2.txt

      - uses: EndBug/add-and-commit@v2
        with:
          message: "Test2"
          path: "."
          pattern: "*.txt"
          cwd: "./pathToRepo/"
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
